// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeBuwbj6ctzkujAkzjQaeQ9Svm7SO6agY',
    appId: '1:753641873408:web:6ce91c52b03f54f5c778e5',
    messagingSenderId: '753641873408',
    projectId: 'newhouseofgenuses',
    authDomain: 'newhouseofgenuses.firebaseapp.com',
    storageBucket: 'newhouseofgenuses.appspot.com',
    measurementId: 'G-PYBMSBPXF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKRkE9JpZt0bxIDUltlu63-ulv8j7vjsg',
    appId: '1:753641873408:android:d6d3164925d1bffdc778e5',
    messagingSenderId: '753641873408',
    projectId: 'newhouseofgenuses',
    storageBucket: 'newhouseofgenuses.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-NlATs8fMlsfWJxWauVzkOj9ZMgghrvU',
    appId: '1:753641873408:ios:072a22c929b51018c778e5',
    messagingSenderId: '753641873408',
    projectId: 'newhouseofgenuses',
    storageBucket: 'newhouseofgenuses.appspot.com',
    iosBundleId: 'hog.odyssey.dev',
  );
}
